// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpxjh_SHwUA1KwNGvuW5V1kcZu0K5U750',
    appId: '1:625899625373:web:e8106663785d8a9f7e6d74',
    messagingSenderId: '625899625373',
    projectId: 'beamapp-a16fe',
    authDomain: 'beamapp-a16fe.firebaseapp.com',
    storageBucket: 'beamapp-a16fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeS9DOh5aEu_uran8_rgBn5pIx3JgmSg8',
    appId: '1:625899625373:android:b4c6af3df686479f7e6d74',
    messagingSenderId: '625899625373',
    projectId: 'beamapp-a16fe',
    storageBucket: 'beamapp-a16fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLA6pAThTFwNszvfNbSzk_n7P0EpWy7BU',
    appId: '1:625899625373:ios:c3dfe59184dc2db17e6d74',
    messagingSenderId: '625899625373',
    projectId: 'beamapp-a16fe',
    storageBucket: 'beamapp-a16fe.appspot.com',
    iosClientId: '625899625373-tp6hthcr9kntne974rf12jmel89ql9j3.apps.googleusercontent.com',
    iosBundleId: 'com.example.beamFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLA6pAThTFwNszvfNbSzk_n7P0EpWy7BU',
    appId: '1:625899625373:ios:c3dfe59184dc2db17e6d74',
    messagingSenderId: '625899625373',
    projectId: 'beamapp-a16fe',
    storageBucket: 'beamapp-a16fe.appspot.com',
    iosClientId: '625899625373-tp6hthcr9kntne974rf12jmel89ql9j3.apps.googleusercontent.com',
    iosBundleId: 'com.example.beamFrontend',
  );
}
